<?php
/**
 * WordPress 
 *
 * @package   ...
 * @author    ...
 * @license   GPL-2.0+
 * @link      
 * @copyright 2014 ...
 */

/*
 @wordpress-plugin
 Plugin Name:       ...
 Plugin URI:        @TODO
 Description:       Qme
 Version:           20.4
 Author:            ...
 Author URI:        @TODO
 Text Domain:       ...
 License:           GPL-2.0+
 Domain Path:       /languages
 GitHub Plugin URI: ...
 GitHub Branch:     master 
 GitHub Access Token: ...
 */
 

...
...
...
?>

